/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_Intersections */

#ifndef _Included_application_Intersections
#define _Included_application_Intersections
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_Intersections
 * Method:    runAllPairs
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_application_Intersections_runAllPairs
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     application_Intersections
 * Method:    runBentleyOttmann
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_application_Intersections_runBentleyOttmann
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
